# Generated by Django 4.1 on 2022-12-03 04:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("user_id", models.CharField(max_length=15)),
                ("index_set_question", models.SmallIntegerField()),
                ("score", models.SmallIntegerField(default=-1)),
            ],
        ),
    ]
