# Generated by Django 4.1 on 2022-12-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_score", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="index_question",
            field=models.SmallIntegerField(default=0),
        ),
    ]
