# Generated by Django 4.1 on 2022-10-16 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("app_questions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SetOfQuestion",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("list_question", models.CharField(max_length=2500)),
            ],
        ),
    ]
